#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width	3
bspc config window_gap		6	
bspc config split_ratio		0.60

# Bar
polybar example &

# Wallpaper
feh --bg-scale $HOME/.config/bspwm/wallpaper.png
